# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 04-runners

on:
   workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        runner: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.runner }}

    steps:
      
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: src/package-lock.json
        
    - run: npm ci
      working-directory: src

    - run: npm run test-cli
      working-directory: src
       
    - run: npm start
      working-directory: src
