# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 05-containers

on:
  workflow_dispatch:

jobs:
  regular:

    runs-on: ubuntu-22.04

    steps:
    - run: cat /etc/lsb-release


  container:

    runs-on: ubuntu-22.04

    container:
      image: ubuntu:18.04

    steps:
    - run: cat /etc/lsb-release
